## 3. Ciclos, tratamiento de fechas





### 1° Parte. Ciclos `while`

**Ejercicio 1.** Si se ingresa $7$ como dividendo y $3$ como divisor ¿cuántas veces se repite la ejecución del cuerpo del `while` en el programa siguiente? ¿Y si los números fueran $48$ y $9$?

In [ ]:
def cociente(num, div: int) -> int:
    """
    pre: num >= 0 and div >= 1
    post: devuelve el cociente de la división de num por div
    """
    coc, resto = 0, num
    while div <= resto:
        coc, resto = coc + 1, resto - div
    return coc

**Respuesta:** para $7$ y $3$, dos veces, para $48$ y $9$ son $5$ veces.

**Ejercicio 2.** ¿Qué ocurre con la función `cociente()` del ejercicio 1 si `num` es negativo y `div` positivo? ¿Y si `num` es positivo y `div` negativo? ¿Y si ambos son negativos?


**Respuesta:** en el caso que `num` es negativo y `div` positivo, la condición del ciclo no se cumple nunca y por lo tanto se devuelve `0`.

Si `num` es positivo y `div` negativo, se cumple en la primera iteración que `div <= num` y luego  romo se hace `resto = resto - div`,  el nuevo resto es más grande cada vez y por lo tanto el ciclo no termina.

Si ambos son negativos y `div <= resto` el ciclo no termina porque `resto` va aumentando. Si `div > resto`,  devuelve  `0`.

**Ejercicio 3.** Escribir en la siguiente celda de código la función `es_primo()` que determina si un número entero dado es primo o no.

**Resouesta:** una forma de  comprobar que un número $n$ es primo es ver que para todo $d$ tal que $1 < d < n$, se cumple que $d$ no divide a $n$. La siguiente función implementa esta verificación.  

In [3]:
# Solución
def es_primo(n: int) -> bool:
    """
    pre: type(n) == int y n > 0.
    pos: Devuelve True si n es primo.
    """
    assert (type(n) == int and n > 0), 'n debe ser un entero positivo'
    primo = True
    if n == 1:
        primo = False
    d = 2
    while d < n:
        if n % d == 0:
            d = n
            primo = False
        else:
            d = d + 1
    return primo

In [ ]:
# Pruebas
print(es_primo(23)) # True
print(es_primo(12)) # False
print(es_primo(1)) # False
print(es_primo(2)) # True
print(es_primo(3)) # True
print(es_primo(4)) # False
print(es_primo(5)) # True
print(es_primo(6)) # False

El programa anterior es correcto, pero en computación es importante también la complejidad del programa,  es decir, esencialmente, el tiempo que tarda. En este aspecto el programa se puede mejorar haciendo dos cambios:

1. Si un número $n$ no es primo,  entonces hay un divisor $d$ tal que $1 < d \le \sqrt{n}$. Luego el `while` debería comprobar hasta  `n**0.5`.
2. Si descubrimos dentro  del `while` un divisor de `n`,  entonces podemos cortar el ciclo.

Teniendo esto en cuenta reescribimos el código.

In [5]:
def es_primo(n: int) -> bool:
    """
    pre: type(n) == int y n > 0.
    pos: Devuelve True si n es primo.
    """
    assert (type(n) == int and n > 0), 'n debe ser un entero positivo'
    primo = True
    if n == 1:
        primo = False
    d = 2
    while d <= n**0.5 and primo == True:
        if n % d == 0:
            d = n
            primo = False
        else:
            d = d +1
    return primo

**Ejercicio 4.** Escribir en la siguiente celda de código la función `factor_pequeno()` que dado un número entero mayor igual que $2$ devuelve su factor primo más pequeño.

**Respuesta:** dado $n \ge 2$,  el divisor más pequeño  mayor que $1$ es primo. Por lo tanto, la función solo encontrará el divisor más pequeño (que será primo).  

In [6]:
# Solución 
def factor_pequeno(n: int) -> int:
    """
    pre:  n entero, n >= 2
    post: devuelve d > 1 tal que d | n y  si d' > 1 y d' | n,  entonces d <= d'
    """
    assert type(n) == int and n >= 2, 'el parámetro debe ser un entero >= 2'
    d = 2
    while  d <= n and n % d != 0:
        d = d + 1
    return d

In [ ]:
print(factor_pequeno(17))
print(factor_pequeno(12))
print(factor_pequeno(161))
print(factor_pequeno(100911))

**Ejercicio 5.** Escribir en la siguiente celda de código una función que dado un número entero imprime todos sus factores primos en orden creciente.

**Respuesta:** podemos usar la función del ejercicio anterior

1. Dado $n$ encontramos $p$ el factor primo más pequeño de $n$.
2. Ahora,  el factor más pequeño de $n/p$ es el siguiente factor más pequeño (y por lo tanto primo) de $n$,
3. Repetimos el esquema del paso 2.  

In [12]:
# Solución
def factores_primos(n):
    """
    pre: n entero,  n >= 2
    pos: imprime todos los factores primos de n, con multiplicidad
    """
    assert type(n) == int and n >= 2, 'el parámetro debe ser un entero >= 2'
    cociente = n
    while cociente > 1:
        d = factor_pequeno(cociente)
        print(d, end=' ')
        cociente = cociente // d
    print('')

In [ ]:
factores_primos(2)
factores_primos(8)
factores_primos(30)
factores_primos(37)
factores_primos(100911)

**Ejercicio 6.** Escribir en la siguiente celda de código la función `max_div_propio()` que dado un número entero positivo devuelve su máximo divisor propio (*propio*  = que no sea el mismo número).


In [15]:
# Solución
def max_div_propio(n):
    divisor = 1
    d = 1
    while d < n:
        if n % d == 0:
            divisor = d
        d += 1
    return  divisor

In [ ]:
# Pruebas
print(max_div_propio(7))
print(max_div_propio(12))
print(max_div_propio(27))
print(max_div_propio(100911))

También se podría hacer el programa en base a la siguiente observación: dado $n$, si $d > 1$ es el divisor más pequeño de $n$, entonces $n/d$  es el divisor propio más grande  de $n$. Por lo tanto,

In [18]:
def max_div_propio(n):
    return n // factor_pequeno(n)

In [ ]:
print(max_div_propio(7))
print(max_div_propio(12))
print(max_div_propio(27))
print(max_div_propio(100911))

**Ejercicio 7.** Escribir en la siguiente celda de código la función `raiz_cuadrada_entera()` que dado un número $n$  devuelve la raíz cuadrada entera de  $n$. La raíz cuadrada entera de $n$, es el número entero $k$ tal que $k^2 \le n < (k+1)^2$. En la solución no se debe utilizar la función `sqrt()` ni potencias fraccionarias.


In [20]:
# Solución
def raiz_cuadrada_entera(n: int) -> int:
    """
    pre: n entero >= 0
    pos: devuelve k tal que k**2 <= n < (k+1)**2
    """
    assert type(n) == int and n >= 0, 'el parámetro debe ser un entero no negativo'
    k = 0
    while k**2 <= n:
        k = k +1
    return k - 1

In [ ]:
# Pruebas
print(raiz_cuadrada_entera(4)) # 2
print(raiz_cuadrada_entera(7)) # 2
print(raiz_cuadrada_entera(18)) # 4
print(raiz_cuadrada_entera(25)) # 5
print(raiz_cuadrada_entera(100911)) # 317

**Ejercicio 8.** Escribir en la siguiente celda de código una función que calcula el máximo común divisor de dos números naturales positivos dados.

**Respuesta:** la forma más directa de  calcular el  máximo común divisor de dos números es recorriendo todos los números no mayores a ambos y ver cual es el mayor que divide a ambos,

In [23]:
# Solución
def mcd(a, b: int) -> int:
    """
    pre: a, b enteros no negativos, alguno de los dos != 0
    pos: devuelve mcd(a,b)
    """
    assert type(a) == type(b) == int and a >= 0 and b>= 0, 'los parámetro deben ser enteros no negativos'
    assert a > 0 or b > 0, 'uno de los parámetros debe ser positivo'
    max_com_div = 1
    d = 1
    cota = min(a, b)
    while d <= cota:
        if a % d ==0 and b % d == 0:
            max_com_div = d
        d += 1
    return  max_com_div

In [ ]:
# Pruebas
print(mcd(5, 14))
print(mcd(2, 6))
print(mcd(8, 24))
print(mcd(18, 24))
print(mcd(19, 17))
print(mcd(28458, 100911))
# print(mcd(195654654656356356, 17563563563563677865465635)) # correr esta linea tarda mucho

Este es un programa correcto pero muy malo a nivel de eficiencia. Debemos utilizar un poco de teoría de la divisibilidad para mejorar, notablemente la eficiencia. El  resultado que utilizaremos es el siguiente: sean $a, b$ no negativos y supongamos que $b>0$, entonces si
\begin{equation*}
a = bq + r,
\end{equation*}
donde $0\le r <b$ (algoritmo de división),  vale lo siguiente
\begin{equation*}
\operatorname{mcd}(a,b) = \operatorname{mcd}(b, r).
\end{equation*}
Aplicando repetidas veces este  razonamiento reducimos el cálculo del $\operatorname{mcd}$ a números cada vez más pequeños. Más aún,  en algún momento llegaremos a que el resto de dividir es $0$ y  ahí usaremos la propiedad de que si $a >0$,  entonces $
\operatorname{mcd}(a, 0) = a$.

Implementemos el algoritmo:

In [28]:
def mcd(a, b: int) -> int:
    """
    pre: a, b enteros no negativos, alguno de los dos != 0
    pos: devuelve mcd(a,b)
    """
    assert type(a) == type(b) == int and a >= 0 and b>= 0, 'los parámetro deben ser enteros no negativos'
    assert a > 0 or b > 0, 'uno de los parámetros debe ser positivo'
    x, y = max(a,b), min(a,b)
    while y > 0:
        x, y = max(x % y, y), min(x % y, y)
    return x

Este algoritmo es llamado el *algoritmo de Euclides.*

In [ ]:
# Pruebas
print(mcd(5, 14))
print(mcd(2, 6))
print(mcd(8, 24))
print(mcd(18, 24))
print(mcd(19, 17))
print(mcd(28458, 100911))
print(mcd(195654654656356356, 17563563563563677865465635))  # correr esta linea es casi instantaneo

**Ejercicio 9.** Escribir en la siguiente celda de código una función que  solicita el ingreso de una respuesta `s` o `n` (por “sí” o “no”? y que ante una respuesta diferente reporta un error y vuelve a solicitar se ingrese  `s` o `n` y sigue de esta manera hasta que finalmente se ha ingresado  `s` o `n`. La función devuelve lo último ingresado.

In [33]:
# Solución
def si_o_no():
    respuesta = input("ingrese 's' o 'n': ")
    while respuesta != 's' and respuesta != 'n':
        respuesta = input("ingrese 's' o 'n'")
    return respuesta

In [32]:
# si_o_no() # descomentar estalínea para probar la función

**Ejercicio 10.**  Escribir en la siguiente celda de código una función que devuelve los valores de la siguiente función:
\begin{equation*}
f(0) = 1,  \qquad f(n) = 2\cdot f(n-1) + n^2\quad \text{si $n\ge 1$}
\end{equation*}

In [34]:
# Solución
def f(n):
    assert type(n) == int  and n >=0
    devuelve = 0
    if n == 0:
        devuelve = 1
    else:
        x = 1
        for i in range(1, n +1):
            x = 2 * x + i**2
        devuelve = x
    return  devuelve


In [ ]:
# Pruebas
print(f(0)) # 1
print(f(1)) # 3
print(f(2)) # 10
print(f(3)) # 29
print(f(30)) # 7516191742

**Ejercicio 11.**  Escribir en la siguiente celda de código una función que devuelve los valores de la siguiente función:
\begin{equation*}
g(0) = 5,  \qquad g(n) = \frac12\cdot g(n-1)^2 + 2n\quad \text{si $n\ge 1$}
\end{equation*}

In [1]:
# Solución
def g(n):
    assert type(n) == int  and n >=0
    devuelve = 0
    if n == 0:
        devuelve = 5
    else:
        x = 5
        for i in range(1, n +1):
            x = (1/2) * x**2 + 2*i
        devuelve = x
    return  devuelve

In [2]:
# Pruebas
for n in range(6):
    print('g(',n,') =', g(n))

"""
Debe imprimir
g( 0 ) = 5
g( 1 ) = 14.5
g( 2 ) = 109.125
g( 3 ) = 5960.1328125
g( 4 ) = 17761599.57131958
g( 5 ) = 157737209665959.94
"""

g( 0 ) = 5
g( 1 ) = 14.5
g( 2 ) = 109.125
g( 3 ) = 5960.1328125
g( 4 ) = 17761599.57131958
g( 5 ) = 157737209665959.94


'\nDebe imprimir\ng( 0 ) = 5\ng( 1 ) = 14.5\ng( 2 ) = 109.125\ng( 3 ) = 5960.1328125\ng( 4 ) = 17761599.57131958\ng( 5 ) = 157737209665959.94\n'

**Ejercicio 12.**  Escribir en la siguiente celda de código una función que devuelve los valores de la siguiente función:
\begin{equation*}
 h(n) = \sum_{i=1}^{n} 2\cdot \operatorname{log}(i) + n\quad \text{si $n\ge 1$}
\end{equation*}

In [6]:
# Solución
from math import log10

def h(n: int):
    """
    pos: h(n)
    """
    assert type(n) == int and n >= 0, 'el parámetro debe ser entero  >= 0'
    suma = 0
    for i in range(1, n + 1):
        suma  = suma + 2 * log10(i)
    return suma + n

In [8]:
# Pruebas
print(h(1)) # 1.0
print(h(2)) # 2.6020599913279625
print(h(3)) # 4.556302500767288
print(h(4)) # 6.760422483423212
print(h(5)) # 9.15836249209525

1.0
2.6020599913279625
4.556302500767288
6.760422483423212
9.15836249209525


**Ejercicio 13.**  Escribir en la siguiente celda de código la función `t()` que devuelve los valores de la siguiente función:
\begin{equation*}
 \sum_{k=0}^n k^2 a^k  \quad \text{si $n\ge 0, a \in \mathbb R$.}
\end{equation*}
En  este caso la función debe depender de dos parámetros: $n$ de tipo `int` y $a$ de tipo `float`.

In [14]:
# Solución
def t(n: int, a:float):
    """
    pre: n entero no negativo, a float
    pos: devuelve \sum_{k=0}^n k**2 * a**k
    """
    assert type(n) == int and (type(a) == float or type(a) == int) and n >= 0, 'el primer parámetro debe ser entero no negativo y el segundo parámetro debe ser float'
    suma = 0
    for k in range(n + 1):
        suma  = suma + k**2 * a**k
    return suma

In [15]:
# Pruebas
n = 10
print(t(n, 1) == n*(n + 1)*(2*n + 1) // 6) # True
print(t(5, 2)) # 1146
print(t(8, -1.5)) # 1081.3828125

True
1146
1081.3828125


**Ejercicio 14.** Sea $\{a_n\}_{n\in\mathbb N_0}$ la sucesión definida recursivamente por

$$\begin{cases}
a_0=1, \\a_1=2, \\a_{n} = \operatorname{log}(3n)a_{n-1}+(n-1)(n-3)a_{n-2}, \text{ para $n\geq 2$}.
\end{cases}$$

Escribir en la siguiente celda de código una función `f` que implemente la sucesión (es decir `f(n)` $= a_n$).


In [16]:
# Solución
from  math import log10

def f(n: int) -> float:
    """
    pre: n entero y n >= 0
    post: devuelve a_n
    """
    assert type(n) == int and n >= 0, ' el parámetro debe ser un entero >= 0'
    ret = 0
    if n == 0:
        ret = 1
    elif n == 1:
        ret = 2
    else:
        # a_n = log10(3*n)*a_(n-1) + (n-1)*(n-3)*a_(n-2)
        x, y = 1, 2 # x == a_0, y == a_1
        for k in range(2,n+1):
            # x es el anterior del anterior de a_k
            # y es el anterior de a_k
            x, y  = y, log10(3*k)*y + (k-1)*(k-3)*x
            # x es el anterior del anterior de a_(k+1)
            # y es el anterior de a_(k+1)
        ret = y
    return ret

In [17]:
# Pruebas
print(f(0)) # 1
print(f(1)) # 2
print(f(2)) # 0.5563025007672873

1
2
0.5563025007672873


**Ejercicio 15.** Sea $\{a_n\}_{n\in\mathbb N_0}$ la sucesión definida recursivamente por

$$\begin{cases}
   a_0=0, \\a_1=7, \\a_{n} = 5a_{n-1}+(1/2)^na_{n-2}, \text{ para $n\geq 2$}.
  \end{cases}$$

Escribir en la siguiente celda de código una función `f` que implemente la sucesión (es decir `f(n)` $= a_n$).


In [19]:
# Solución
def f(n: int) -> float:
    """
    pre: n entero y n >= 0
    post: devuelve a_n
    """
    assert type(n) == int and n >= 0, ' el parámetro debe ser un entero >= 0'
    ret = 0
    if n == 0:
        ret = 0
    elif n == 1:
        ret = 7
    else:
        # a_n = 5*a_(n-1) + ((1/2)**n * a_(n-2)
        x, y = 1, 2 # x == a_0, y == a_1
        for k in range(2,n+1):
            # x es el anterior del anterior de a_k
            # y es el anterior de a_k
            x, y  = y, 5 * y + (1/2)**k * x
            # x es el anterior del anterior de a_(k+1)
            # y es el anterior de a_(k+1)
        ret = y
    return ret

In [20]:
# Pruebas
print(f(0)) # 0
print(f(1)) # 7
print(f(2)) # 10.25
print(f(3)) # 51.5
print(f(4)) # 258.140625

0
7
10.25
51.5
258.140625


### 2° Parte. Tratamiento de fechas



**Ejercicio 16.**  Escribir en la siguiente celda de código la función `numero_dias()` que  reciba una fecha (tres parámetros: día, mes y año) y devuelva el número de días a de la era moderna hasta ese día. Es decir, si le paso como fecha 1/1/1 me devuelve 1. Si le paso como fecha 31/12/1 devuelve 365. Si le paso 1/1/2 devuelve 366. Si le paso como fecha 4/7/1995, devuelve 728478. Si le paso 15/4/2020 devuelve 737530.


**Respuesta:** vamos a necesitar saber que años son bisiestos. Un  posible función para averiguarlo es:

In [ ]:
# Un  año es bisiesto si es divisible por 4, salvo que seamúltiplo de 100  y  no de 400
def es_bisiesto(año):
    assert type(año) == int and año >=1, 'el parámetro debe ser un entero positivo'
    bis = False
    if año % 4 == 0:
        if año % 100 != 0:
            bis = True
        else:
            if año % 400 == 0:
                bis = True
    return bis

También hay una forma más corta de definir la función:

In [21]:
def es_bisiesto(año):
    assert type(año) == int and año >=1, 'el parámetro debe ser un entero positivo'
    return (año % 4 == 0  and año % 100 != 0) or año % 400 == 0

Por otro lado, debemos comprobar que la fecha ingresada es correcta. Es decir la función para averiguar el número de días recibirá 3 parámetros `dd`, `mm`, `aaaa` y debemos comprobar si ese día existe.

In [22]:
def fecha_correcta(dd, mm, aaaa):
    dias_meses = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    devuelve = True
    if aaaa < 1 or (mm < 1 or mm > 12) or dd < 1:
        devuelve = False
    else:
        # ahora 1 <= aaa, 1 <= mm <= 12 y dd >=1
        if mm !=2:
            if dd > dias_meses[mm-1]:
                devuelve = False
        else:
            if (es_bisiesto(aaaa) and dd > 29) or (not es_bisiesto(aaaa) and dd > 28):
                devuelve = False
    return devuelve

O una versión más corta


In [23]:
def fecha_correcta(dd, mm, aaaa):
    dias_meses = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    devuelve = (1 <= aaaa) and (1 <= mm <= 12) and (1 <= dd <= dias_meses[mm-1])
    if mm == 2 and not es_bisiesto(aaaa) and dd > 28:
        devuelve = False
    return devuelve

Finalmente, escribimos la función solicitada:

In [24]:
def numero_dias(dd, mm, aaaa: int):
    assert fecha_correcta(dd, mm, aaaa), 'fecha incorrecta'
    dias_meses = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    devolver = 0
    for año in range(1, aaaa):
        if es_bisiesto(año):
            devolver = devolver + 366
        else:
            devolver = devolver + 365
    for mes in range(mm - 1):
        if mes != 1:
            devolver = devolver + dias_meses[mes]
        elif mes == 1 and not es_bisiesto(aaaa):
            devolver = devolver + 28
        else:
            devolver = devolver + 29

    return  devolver + dd

In [25]:
# Pruebas
print(numero_dias(1, 1, 1)) # 1
print(numero_dias(31, 12, 1)) # 365
print(numero_dias(1, 1, 2)) # 366
print(numero_dias(4, 7, 1995)) # 728478
print(numero_dias(15, 4, 2020)) # 737530

1
365
366
728478
737530


**Ejercicio 17.** Escribir en la siguiente celda de código la función `dia_semana()` que reciba una fecha (tres parámetros) y devuelve una cadena de caracteres: `lunes` o `martes` o `miércoles` o ... o `domingo`,  que es el día de la semana correspondiente.

Para hacer la función debe considerarse que el 1 de enero del año 1 fue lunes y luego utilizar la función `numero_dias()` definida anteriormente.

In [26]:
# Solución
def dia_semana(dd, mm, aaaa):
    # pre:
    # post:
    # assert ...
    # Hoy es martes 16/04/2024
    dia = ''
    n_dias = numero_dias(dd, mm, aaaa)
    if n_dias % 7 == 2:
        dia = 'martes'
    elif n_dias % 7 == 3:
        dia = 'miércoles'
    elif n_dias % 7 == 4:
        dia = 'jueves'
    elif n_dias % 7 == 5:
        dia = 'viernes'
    elif n_dias % 7 == 6:
        dia = 'sábado'
    elif n_dias % 7 == 0:
        dia = 'domingo'
    elif n_dias % 7 == 1:
        dia = 'lunes'
    return dia

In [ ]:
print(dia_semana(16,4,2024)) # martes
print(dia_semana(26,4,2024)) # viernes
print(dia_semana(1,1,1)) # lunes
print(dia_semana(3,3,2004)) # miércoles

**Ejercicio 18.** Escribir en la siguiente celda de código un programa que solicita que se ingrese la fecha e imprima el día de la semana utilizando la función del ejercicio anterior.

In [ ]:
# Solución
# Descomentar lo que sigue para probar el código
"""
dia = int(input('dia='))
mes = int(input('mes='))
año = int(input('año='))
print(dia_semana(dia, mes, año))
"""

**Ejercicio 19.** Escribir en la siguiente celda de código la función `fecha_x_numero_dias()` que dado un número de días a contar a partir del 31/12/añocero devuelve una terna dia/mes/año. Por ejemplo, si lo llamo con 728478 devuelve 4/7/1995. Si le paso 737530 me devuelve 15/4/2020.

**Rspuesta:** este es un programa más complicado que los anteriores. Supongamos que todos lo años tengan 365 días y todos los meses tengan 30  días. La idea es ir descontando a los días que se ingresan como input, los años x 365 hasta que queden menos de 365 días y eso determina el año. Con los meses algo parecido, ir descontando 30  días por mes hasta que queden menos de 30  días, lo cual determinará el mes. Los días que quedan determinan el día correspondiente a la fecha. El algoritmo se complica un poco debido a los años bisiestos y a que los meses tienen duración varibale.

In [27]:
def fecha_x_numero_dias(n_dias: int) -> tuple:
    # pre: n_dias >= 1
    # post: devuelve la fecha
    año = 1
    numero_dias = 0
    while numero_dias < n_dias:
        numero_dias_anterior = numero_dias
        if es_bisiesto(año):
            numero_dias += 366
        else:
            numero_dias += 365
        año += 1
    año = año - 1
    numero_dias = numero_dias_anterior
    dias_meses = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    meses = ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic']
    i = 0
    mes = 0
    while numero_dias < n_dias:
        numero_dias_anterior = numero_dias
        if mes == 1:
            if es_bisiesto(año):
                numero_dias += 29
            else:
                numero_dias += 28
        else:
            numero_dias += dias_meses[mes]
        mes += 1
    numero_dias = numero_dias_anterior + 1
    dia = 0
    dia = n_dias - numero_dias + 1
    return dia,  mes,  año

In [28]:
# Pruebas
print(fecha_x_numero_dias(1)) # 1/1/1
print(fecha_x_numero_dias(365)) # 31/12/1
print(fecha_x_numero_dias(1+365)) # 1/1/2
print(fecha_x_numero_dias(1+365+365)) # 1/1/3
print(fecha_x_numero_dias(1+365+365+365)) # 1/1/4
print(fecha_x_numero_dias(1+365+365+365+365)) # 31/12/4
print(fecha_x_numero_dias(1+365+365+365+365+1)) # 1/1/5
print(fecha_x_numero_dias(728478)) # 4/7/1995
print(fecha_x_numero_dias(737530)) # 15/4/2020

(1, 1, 1)
(31, 12, 1)
(1, 1, 2)
(1, 1, 3)
(1, 1, 4)
(31, 12, 4)
(1, 1, 5)
(4, 7, 1995)
(15, 4, 2020)


**Ejercicio 20.** Escribir en la siguiente celda de código la función `fecha_dif_dias()` que dada una fecha `dia`, `mes`, `año` y un número positivo `n` de días, devuelve la fecha que se obtiene `n` días después de la fecha dada. Por ejemplo, si le paso `15`, `4`, `2020` y `1` devuelve `16`, `4`, `2020`. Si le paso `4`, `7`, `1995` y `9052`devuelve `15`, `4`, `2020`.

**Respuesta:** este ejercicio lo podemos hacer utilizando las funciones anteriores. Primero con `numero_dias()` calculamos el número de días hasta la fecha actual y le sumamos `n`. Esto nos resultará en el número de días de la fecha que buscamos. Con la función `fecha_x_numero_dias()` recuperamos la fecha de ese día.

In [29]:
# Solución
def fecha_dif_dias(dia, mes , año, n):
    nro_dias_fecha = numero_dias(dia, mes ,año) + n
    return fecha_x_numero_dias(nro_dias_fecha)

In [30]:
# Pruebas
print(fecha_dif_dias(15, 4, 2020, 1)) # (16, 4, 2020)
print(fecha_dif_dias(4, 7, 1995, 9052)) # (15, 4, 2020)

(16, 4, 2020)
(15, 4, 2020)


**Ejercicio 21.** Escribir en la siguiente celda de código la función `dif_dias_fechas()` que dadas dos fechas devuelve la cantidad de días que las separa.


In [31]:
# Solución
def dif_dias_fechas(dia0, mes0 ,año0, dia1, mes1 ,año1):
    return abs(numero_dias(dia1, mes1 ,año1) -  numero_dias(dia0, mes0 ,año0))

In [32]:
# Pruebas
print(dif_dias_fechas(15, 4, 2020, 16, 4, 2020)) # 1
print(dif_dias_fechas(4, 7, 1995, 15, 4, 2020)) # 90952

1
9052
